########################### Server configurations ####################################
server:
  port: 8090

###################### Spring configurations for database and mail service ################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: gms-sure-trade.postgres.database.azure.com
    port: 5432
    username: gms@gms-sure-trade
    password: Password12#
    database: betasavemgtdb
    url: jdbc:postgresql://gms-sure-trade.postgres.database.azure.com:5432/betasavemgtdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host:
    port: 465
    username: talk2wahab247@gmail.com
    password: xqllqmrlgmsslixp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

######################## Custom configurations #######################
betasave:
  security:
    jwt:
      secret: c1zJs5rugZn2nTcavvIs45QPmFMCjYnyc1zJs5rugZn2nTca
      expirationInMinutes: 30
  otp:
    signup:
      expirationTimeInMin: 10

###################### Paystack Configuration ############################
paystack:
  secretKey: sk_test_0ffaa22ee10152d638781bdc0ccc14322124f3ee
  publicKey: pk_test_a40841d9a1b3ef020356cad9d270f38e37f41c7c
  initializationUrl: https://api.paystack.co/transaction/initialize
  verifyTransactionUrl: https://api.paystack.co/transaction/verify/