########################### Server configurations ####################################
server:
  port: 8090



###################### Spring configurations for database and mail service ################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: dpg-cgq83be4dadce834c84g-a
    port: 5432
    username: root
    password: c1zJs5rugZn2nTcavvIs45QPmFMCjYny
    database: betasavemgtdb
    url: jdbc:postgresql://dpg-cgq83be4dadce834c84g-a.oregon-postgres.render.com:5432/betasavemgtdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: talk2wahab247@gmail.com
    password: xqllqmrlgmsslixp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

######################## Custom configurations #######################
betasave:
  security:
    jwt:
      secret: c1zJs5rugZn2nTcavvIs45QPmFMCjYnyc1zJs5rugZn2nTca
      expirationInMinutes: 30
  otp:
    signup:
      expirationTimeInMin: 10